version: '2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network
    ports:
       - "8080:8080"
    environment:
      DATABASE_URL: postgresql://postgres:secret@db:5432
      RUST_BACKTRACE: 1
      RUST_LOG: microservice=debug
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    networks:
      - network
    ports:
      - "5432"
    environment:
      POSTGRES_PASSWORD: secret

networks:
  network: